<?php if(!defined("__XE__")) exit();
$db_info = (object)array (
  'master_db' => 
  array (
    'db_type' => 'mysql',
    'db_port' => '3306',
    'db_hostname' => '127.0.0.1',
    'db_userid' => 'root',
    'db_password' => 'mayday0929',
    'db_database' => 'mysql',
    'db_table_prefix' => 'xe_',
  ),
  'slave_db' => 
  array (
    0 => 
    array (
      'db_type' => 'mysql',
      'db_port' => '3306',
      'db_hostname' => '127.0.0.1',
      'db_userid' => 'root',
      'db_password' => 'mayday0929',
      'db_database' => 'mysql',
      'db_table_prefix' => 'xe_',
    ),
  ),
  'default_url' => 'http://127.0.0.1/michellu/xe/',
  'lang_type' => 'zh-CN',
  'use_mobile_view' => 'Y',
  'use_rewrite' => 'Y',
  'time_zone' => '+0800',
  'use_prepared_statements' => 'Y',
  'qmail_compatibility' => 'N',
  'use_db_session' => 'N',
  'use_ssl' => 'none',
  'sitelock_whitelist' => 
  array (
    0 => '127.0.0.1',
  ),
  'embed_white_object' => 
  array (
    0 => '//www.youtube-nocookie.com/',
    1 => '//www.youtube.com/embed/',
    2 => '//www.youtube.com/v/',
    3 => 'http://api.v.daum.net/',
    4 => 'http://blogdoc.nate.com/flash/blogdoc_widget_reco.swf',
    5 => 'http://dbi.video.cyworld.com/v.sk/',
    6 => 'http://doc.mgoon.com/player/',
    7 => 'http://event.dn.naver.com/sbsplayer/vmplayer.xap',
    8 => 'http://flvr.pandora.tv/flv2pan/',
    9 => 'http://flvs.daum.net/flvPlayer.swf',
    10 => 'http://imgcdn.pandora.tv/gplayer/flJal.swf',
    11 => 'http://imgcdn.pandora.tv/gplayer/pandora_EGplayer.swf',
    12 => 'http://musicplayer.naver.com/naverPlayer/posting/',
    13 => 'http://netv.sbs.co.kr/sbox/silverlight/ClientBin/NeTVPlayer.xap',
    14 => 'http://news.sbs.co.kr/',
    15 => 'http://onemore.imbc.com/ClientBin/oneplus.xap',
    16 => 'http://play.mgoon.com/Game/',
    17 => 'http://play.mgoon.com/Photo/',
    18 => 'http://play.mgoon.com/Video/',
    19 => 'http://play.tagstory.com/player/',
    20 => 'http://player.music.naver.com/naverPlayer/posting/',
    21 => 'http://sbsplayer.sbs.co.kr/',
    22 => 'http://scrap.ad.naver.com/',
    23 => 'http://serviceapi.nmv.naver.com/',
    24 => 'http://static.campaign.naver.com/0/campaign/2010/10/socialsearch/swf/',
    25 => 'http://tvpot.daum.net/playlist/playlist.swf',
    26 => 'http://v.egloos.com/v.sk/',
    27 => 'http://v.nate.com/v.sk/',
    28 => 'http://vmark.kbs.co.kr/zzim/vmplayer/vmplayer.xap',
    29 => 'http://w.blogdoc.nate.com/',
    30 => 'http://wizard2.sbs.co.kr/',
    31 => 'http://www.kbs.co.kr/zzim/vmplayer/vmplayer.xap',
    32 => 'http://www.tagstory.com/player/basic/',
    33 => 'http://www.youtube-nocookie.com/',
    34 => 'http://www.youtube.com/v/',
  ),
  'embed_white_iframe' => 
  array (
    0 => '//www.youtube-nocookie.com/',
    1 => '//www.youtube.com/embed/',
    2 => '//www.youtube.com/v/',
    3 => 'http://flvs.daum.net/',
    4 => 'http://maps.google.co.kr/',
    5 => 'http://maps.google.com/',
    6 => 'http://player.vimeo.com/',
    7 => 'http://sbsplayer.sbs.co.kr/',
    8 => 'http://www.youtube-nocookie.com/',
    9 => 'http://www.youtube.com/',
    10 => 'https://www.youtube-nocookie.com/',
    11 => 'https://www.youtube.com/',
  ),
);